config/routes.rb
MusicApp::Application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  root to: redirect("/users/new")
  resources :bands, only: [:new, :create, :show, :index] do
     resources :albums, only: [:new]
  end
  resources :albums, only: [:new, :create, :show, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:new, :create, :show, :destroy]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  band_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
  validates :name, :band_id, presence: true
  belongs_to :band
  has_many :tracks, dependent: :destroy

end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :tracks
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  lyrics     :text
#  track_type :string(255)      default("regular")
#  album_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base
  belongs_to :album
  has_one :band, through: :album, source: :band
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :email, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true

  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom.base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :redirect_unless_logged_in
  def new
    @band = Band.find(params[:band_id])
    @bands = Band.all
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      fail
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def destroy
    @album = Album.find(params[:id])
    @band = @album.band
    @album.delete
    flash[:success] = ['album deleted']
    redirect_to band_url @band
  end

  private
  def album_params
    params.require(:album).permit(:name, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?

  def current_user
    return nil if @user.nil?
    User.find_by(session_token: @user.session_token)
  end
  def logged_in?
    # @user = User.find_by(session_token: session[:session_token])
    current_user ? true : false
  end
  def user_params
    params.require(:user).permit(:email, :password)
  end
  def redirect_unless_logged_in
    if !logged_in? then redirect_to new_user_url end
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :redirect_unless_logged_in
  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def destroy
  end

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #get request to session/new returns log in page
  def new
    @user = User.new
    render :log_in
  end

  #post to session runs create action
  def create
    @user = User.find_by_credentials(params[:user][:email],params[:user][:password])

    if @user.nil?
      flash.now[:errors] = ["incorrect email/password combination"]
      render :log_in
    else
      @user.reset_session_token!
      session[:session_token] = @user.session_token
      # fail
      redirect_to user_url(@user)
    end
  end

  def destroy
    user = User.find_by(session_token: session[:session_token])
    if user.nil?
      raise "logout failure"
    else
      user.reset_session_token!
      session[:session_token] = nil
      redirect_to new_sessions_url
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :redirect_unless_logged_in
  def new
    @album = Album.find(params[:album_id])
    @albums = Album.all
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url @track
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    @album = @track.album
    render :show
  end

  def destroy
    @track = Track.find(params[:id])
    @album = @track.album
    @track.delete
    flash[:success] = ["track deleted"]
    redirect_to album_url @album
  end

  private
  def track_params
    params.require(:track).permit(:name, :album_id, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_unless_logged_in, except: [:new, :create]
  #new action called from a get request to /users/new
  #responds by sending a form to create a new user
  def new
    @user = User.new
    render :new
  end

  def index
    @users = User.all
    render :index
  end
  #create action called from a post request to /users
  #attempts to create a new user using the params that accompanied
  #the post request. Params must be whitelisted
  def create
    @user = User.new(user_params)
    session[:session_token] = @user.session_token
    if @user.save
      redirect_to user_url(@user) #will call the show action for the user view
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    #render :show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticate_form
    <<-HTML.html_safe
    <input type="hidden"
    name="authenticity_token"
    value="#{form_authenticity_token}">
    HTML

  end
end

app/views/albums/new.html.erb
<form class="" action="/albums" method="post">
  <%= authenticate_form %>
  <label for="album name">Album Name</label>
  <input type="text" name="album[name]" value="">
  <label for="band">Band</label>
  <select class="" name="album[band_id]">
    <% @bands.each do |band| %>
    <option value="<%=band.id%>" <%= unless @band.nil? then
      @band.id == band.id ? "selected" : "" end%> ><%= band.name %> </option>
    <% end %>
  </select>
  <button>Submit!</button>
</form>
<a href="<%= bands_url %>">All Bands</a><br>
<a href="<%= new_band_url %>">Start a new band!</a>

app/views/albums/show.html.erb
<h1><%= @album.name %> by <%= @album.band.name %></h1>
<% i = 0 %>
<% @album.tracks.each do |track| %>
<%= i += 1 %>. <%= track.name %> <a href=" <%= track_url(track) %>">
   Track Page </a>  <%= render "shared/delete_track_button", track: track %><br>
<% end %><br>
<a href="<%= new_album_track_url(@album) %>">New track</a><br>
<a href="<%= band_url(@album.band) %>"><%= @album.band.name %>'s band page</a><br>
<a href="<%= bands_url %>">All Bands</a><br>

<a href="<%= new_band_url %>">Start a new band!</a>

app/views/bands/index.html.erb
<ul>
<% @bands.each do |band| %>
<li><%= band.name %> <a href="<%= band_url(band)%>">band page</a>
<a href="<%=new_band_album_url(band)%>">add an album</a></li>
<% end %>
</ul><br>
<a href="<%= new_band_url %>">Start a new band!</a>

app/views/bands/new.html.erb
<form class="" action="/bands" method="post">
  <label for="band_name">Band Name</label>
  <%= authenticate_form %>
  <input type="band_name" name="band[name]" value="">
  <button>Submit</button>
</form>

app/views/bands/show.html.erb
<h1>The page for <%= @band.name %></h1>
Their ablums include:
<ul>
  <% @band.albums.each do |album| %>
  <li><%= album.name %> <a href="<%= album_url(album) %>">album link</a></li>
  <%= render "shared/delete_album_button", album: album %>
  <% end %>
</ul>
<a href="<%= bands_url %>">All Bands</a><br>
<a href="<%= new_band_album_url(@band) %>">add an album</a><br>
<a href="<%= new_band_url %>">Start a new band!</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>


  <%= csrf_meta_tags %>


</head>
<body>

  <% if flash[:success] %>
  <ul>
    <% flash[:success].each do |item| %>
    <li><%=item%></li>
    <%end%><br>
  </ul>
  <% end %>

  <% if flash[:errors]  %>
    <br>
    <ul>
    <% flash[:errors].each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>

  <% if logged_in? %>
    Hello <%= @user.email %>
    <form  action="/sessions" method="post">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="form_authenticity_token">
      <button>Logout</button>
  </form>
  <% else %>
    <a href="/users/new">Sign up</a>
  <% end %>
<%= yield %>

</body>

</html>

app/views/shared/_delete_album_button.html.erb
<form class="" action="<%= album_url(album) %>" method="post">
  <%= authenticate_form %>
  <input type="hidden" name="_method" value="delete">
  <button>Delete Album</button>
</form>

app/views/shared/_delete_track_button.html.erb
<form class="" action="<%= track_url(track) %>" method="post">
  <%= authenticate_form %>
  <input type="hidden" name="_method" value="delete">
  <button>Delete Track</button>
</form>

app/views/tracks/new.html.erb
<form class="" action="<%= tracks_url %>" method="post">
  <%= authenticate_form %>
  <label for="track name">Track Name</label>
  <input type="text" name="track[name]" value=""><br>
  <label for="lyrics">Lyrics</label>
  <textarea name="track[lyrics]" value="" rows="4" cols="50"></textarea><br>
  <label for="album">Album</label>
  <select class="" name="track[album_id]">
    <% @albums.each do |album| %>
    <option value="<%=album.id%>" <%= unless @album.nil? then
      @album.id == album.id ? "selected" : "" end%> ><%= album.name %> </option>
    <% end %>
  </select>
  <button>Submit!</button>
</form>
<a href="<%= bands_url %>">All Bands</a><br>
<a href="<%= albums_url %>">All Albums</a><br>
<a href="<%= new_band_url %>">Start a new band!</a>

app/views/tracks/show.html.erb
<h1>Track page for <%= @track.band.name %>'s <%= @track.name %> off
  of <%= @album.name %></h1>
Lyrics: <%= "#{@track.lyrics}".html_safe %><br>

<%= render "shared/delete_track_button", track: @track %>

<a href="<%= band_url(@album.band) %>"><%= @album.band.name %>'s band page</a><br>
<a href="<%= new_album_track_url(@album) %>">New track</a><br>
<a href="<%= album_url(@album) %>"><%= @album.name %>'s album page</a><br>
<a href="<%= bands_url %>">All Bands</a><br>
<a href="<%= new_band_url %>">Start a new band!</a>

app/views/users/new.html.erb
<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="email">Email</label>
  <input type="text" name="user[email]" value="<%= @user.email %>">
  <br>
  <label for="password">Password</label>
  <input type="password" name="user[password]" value="">
  <button>Submit!</button>
</form>
<a href="<%= new_sessions_url %>">log in</a>

app/views/users/show.html.erb
<%= @user.email %><br>
created at: <%= @user.created_at.to_formatted_s(:short) %><br>
updated at: <%= @user.updated_at.to_formatted_s(:short) %>